create table person (
                        person_id     integer generated by default as identity primary key,
                        fio           varchar not null unique,
                        year_of_birth integer not null
);

INSERT INTO person(fio, year_of_birth) VALUES ('Almina', 2001);
INSERT INTO person(fio, year_of_birth) VALUES ('Diyar', 2001);
INSERT INTO person(fio, year_of_birth) VALUES ('Azamat', 1999);
INSERT INTO person(fio, year_of_birth) VALUES ('Alisher', 1998);
INSERT INTO person(fio, year_of_birth) VALUES ('Vladimir', 2000);
INSERT INTO person(fio, year_of_birth) VALUES ('Nikita', 1999);
INSERT INTO person(fio, year_of_birth) VALUES ('Karina', 1999);
INSERT INTO person(fio, year_of_birth) VALUES ('Amina', 2001);
INSERT INTO person(fio, year_of_birth) VALUES ('Balnur', 1999);

create table book (
    book_id      integer generated by default as identity primary key,
    person_id    integer references person ON DELETE SET NULL,
    title        varchar not null,
    author       varchar not null,
    product_date integer not null
);


INSERT INTO book(title, author, product_date) VALUES ('Anna Karenina', 'Leo Tolstoy', 1878);
INSERT INTO book(title, author, product_date) VALUES ('Madame Bovary', 'Gustave Flaubert', 1856);
INSERT INTO book(title, author, product_date) VALUES ('War and Peace', 'Leo Tolstoy', 1865);
INSERT INTO book(title, author, product_date) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 1920);
INSERT INTO book(title, author, product_date) VALUES ('Lolita', 'Vladimir Nabokov', 1955);
INSERT INTO book(title, author, product_date) VALUES ('Middlemarch', 'George Eliot', 1869);
INSERT INTO book(title, author, product_date) VALUES ('The Adventures of Huckleberry Finn', 'Mark Twain', 1884);
INSERT INTO book(title, author, product_date) VALUES ('The Stories of Anton Chekhov', 'Anton Chekhov', 1932);
INSERT INTO book(title, author, product_date) VALUES ('In Search of Lost Time', 'Marcel Proust', 1913);
INSERT INTO book(title, author, product_date) VALUES ('Hamlet', 'William Shakespeare', 1601);
INSERT INTO book(title, author, product_date) VALUES ('Moby Dick', 'Herman Melville', 1851);